 [mgr]
prepend_keymap = [        
 {  on = [ "m", "m" ], run = "linemode mtimev2", desc = "Linemode: modified time" }, # custom linemode to show time in iso format
 {  on = [ "c", "z" ], run = "shell 'cd \"$(dirname \"$1\")\" && zip -r \"$(basename \"$1\").zip\" -- \"${@##*/}\"' --confirm", desc = "Zip selected into archive" },
 ]
